#' Convert Data Frame Columns to Time Series with Date Column
#'
#' This function converts each numeric column in a data frame into a time series
#' object using the base R \code{ts} function. In addition, it adds a time variable as
#' a Date vector reflecting the frequency of the data (annual, quarterly, or monthly)
#' using a calendar start date.
#'
#' @param df A data frame containing the data to be converted.
#' @param start The start time for the time series. For annual series use a single
#'   numeric year (e.g. 2010). For monthly and quarterly series, use a vector of the
#'   form \code{c(year, period)} (e.g. \code{c(2010, 1)} for January 2010 or Q1 of 2010).
#' @param period A character string indicating the frequency of the time series.
#'   One of \code{"annual"}, \code{"quarterly"}, or \code{"monthly"}. Default is
#'   \code{"annual"}.
#'
#' @return A data frame in which every numeric column is converted to a time series
#'   (\code{ts}) object and a new column named \code{Time} contains Date objects marking
#'   the start of each observation period.
#'
#' @details
#' The function maps the selected period to a numeric frequency required by \code{ts}:
#'
#' \itemize{
#'   \item \code{"annual"}: \code{frequency = 1}.
#'   \item \code{"quarterly"}: \code{frequency = 4}.
#'   \item \code{"monthly"}: \code{frequency = 12}.
#' }
#'
#' A helper function calculates the starting Date given the input \code{start} and \code{period}.
#' The date sequence is generated by \code{\link{seq.Date}}, with the interval set to one year,
#' three months, or one month, accordingly.
#'
#' @examples
#' # Example: Converting a data frame with monthly data
#' df <- data.frame(
#'   sales = c(100, 150, 200, 250),
#'   profit = c(50, 60, 70, 80),
#'   category = c("A", "B", "A", "C")
#' )
#'
#' # Convert numeric columns to time series with a monthly frequency starting in January 2020
#' monthly_df <- tsconvert(df, start = c(2020, 1), period = "monthly")
#'
#' # Inspect the structure. 'sales' and 'profit' are now ts objects,
#' # and a 'Time' column with calendar dates has been added.
#' str(monthly_df)
#'
#' # Example: Converting to an annual time series starting in 2010
#' annual_df <- tsconvert(df, start = 2010, period = "annual")
#' head(annual_df$Time)
#'
#' @export
tsconvert <- function(df, start, period = "annual") {
  # Map the period string to frequency
  frequency <- switch(tolower(period),
                      "monthly"   = 12,
                      "quarterly" = 4,
                      "annual"    = 1,
                      stop("Invalid period specified. Use 'annual', 'quarterly', or 'monthly'.")
  )

  # Determine the number of rows in the data frame
  n <- nrow(df)

  # Helper function: convert 'start' and 'period' to a Date object
  get_start_date <- function(start, period) {
    p <- tolower(period)
    if (p == "annual") {
      # When 'start' is a year (e.g., 2010), use January 1st.
      return(as.Date(sprintf("%d-01-01", start)))
    } else if (p == "monthly") {
      # For monthly data: start should be c(year, month), e.g., c(2010, 1)
      year <- start[1]
      mon  <- start[2]
      return(as.Date(sprintf("%d-%02d-01", year, mon)))
    } else if (p == "quarterly") {
      # For quarterly data: start should be c(year, quarter), e.g., c(2010, 1) for Q1.
      year <- start[1]
      q    <- start[2]
      # Convert quarter (1 to 4) to the appropriate month (1, 4, 7, or 10)
      mon  <- (q - 1) * 3 + 1
      return(as.Date(sprintf("%d-%02d-01", year, mon)))
    } else {
      stop("Invalid period specified. Use 'annual', 'quarterly', or 'monthly'.")
    }
  }

  # Create the starting Date for the sequence
  start_date <- get_start_date(start, period)

  # Determine the interval for the date sequence based on the period
  by_value <- switch(tolower(period),
                     "annual"    = "year",
                     "quarterly" = "3 months",
                     "monthly"   = "month")

  # Generate a sequence of Dates equal in length to the number of data frame rows
  date_seq <- seq.Date(from = start_date, by = by_value, length.out = n)

  # Convert each numeric column to a time series (ts) object
  ts_cols <- lapply(df, function(col) {
    if (is.numeric(col)) {
      ts(col, start = start, frequency = frequency)
    } else {
      col
    }
  })

  # Reassemble the data frame from the list
  new_df <- as.data.frame(ts_cols)

  # Add a new column 'Time' containing the generated Date sequence
  new_df$Date <- date_seq

  return(new_df)
}
